age = int(input("please tell me your age: "))
print(f"you are currently {age} years old.")
print(f"In 10 years,you'll be {age + 10}years old.")
print(f"In 20 years,you'll be {age + 20}years old.")
print(f"in 30 years,you'll be {age + 30}years old.")